name: Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VERSION: 1.0.6
  BUILD_CONFIGURATION: Release
  SERVER_NAME: "The Heroes Journey"
  FILE_NAME: "heroesjourneyeq"
  FILELIST_URL: "https://github.com/BND10706/THJ-Patcher/releases/latest/download/"
  PATCHER_URL: "https://github.com/BND10706/THJ-Patcher/releases/latest/download/"
  STORAGE_URL: "https://patch.heroesjourneyemu.com/rof/"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Generate manifest
      run: npm start

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cd "THJPatcher" && nuget restore "THJPatcher.sln"

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd "THJPatcher" && msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:VERSION="${{ env.VERSION }}.${{ github.run_number }}" /p:FILELIST_URL=${{env.FILELIST_URL}} /p:SERVER_NAME="${{env.SERVER_NAME}}" /p:FILE_NAME="${{env.FILE_NAME}}" "THJPatcher.sln"

    - name: Debug Build Output
      run: |
        Write-Host "=== Current Directory ==="
        Get-Location
        Write-Host "`n=== Directory Structure ==="
        Get-ChildItem -Path "THJPatcher" -Recurse -Filter "*.exe" | ForEach-Object {
            Write-Host $_.FullName
        }

    - name: Generate filelist
      run: |
        cd "rof"
        C:\msys64\usr\bin\wget.exe --no-verbose https://github.com/xackery/filelistbuilder/releases/latest/download/filelistbuilder-win-x64.exe
        Write-Host "=== Running FilelistBuilder ==="
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Looking for executable at: ../THJPatcher/THJPatcher/bin/Release/net8.0-windows/win-x64/THJPatcher.exe"
        if (Test-Path "../THJPatcher/THJPatcher/bin/Release/net8.0-windows/win-x64/THJPatcher.exe") {
            Write-Host "Executable found!"
        } else {
            Write-Host "Executable not found!"
            Write-Host "Checking parent directories..."
            Get-ChildItem -Path "../THJPatcher" -Recurse -Filter "*.exe" | ForEach-Object {
                Write-Host $_.FullName
            }
        }
        .\filelistbuilder-win-x64.exe "rof" "${{env.STORAGE_URL}}" "../THJPatcher/THJPatcher/bin/Release/net8.0-windows/win-x64/THJPatcher.exe"
        move "../THJPatcher/THJPatcher/bin/Release/net8.0-windows/win-x64/THJPatcher.exe" "../THJPatcher/THJPatcher/bin/Release/net8.0-windows/win-x64/${{env.FILE_NAME}}.exe"
        move THJPatcher-hash.txt ${{env.FILE_NAME}}-hash.txt
  
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.VERSION }}.${{ github.run_number }}"
        prerelease: false
        title: "${{ env.VERSION }}.${{ github.run_number }}"
        files: |
          THJPatcher/THJPatcher/bin/Release/net8.0-windows/win-x64/${{env.FILE_NAME}}.exe
          rof/filelist_rof.yml
          rof/${{env.FILE_NAME}}-hash.txt
          manifest.json
