name: Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VERSION: 1.0.6
  BUILD_CONFIGURATION: Release
  SERVER_NAME: "The Heroes Journey"
  FILE_NAME: "heroesjourneyeq"
  FILELIST_URL: "https://github.com/BND10706/THJ-Patcher/releases/latest/download/"
  PATCHER_URL: "https://github.com/BND10706/THJ-Patcher/releases/latest/download/"
  STORAGE_URL: "https://patch.heroesjourneyemu.com/rof/"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Generate manifest
      run: npm start

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore "THJPatcher/THJPatcher.sln"

    - name: Build Application
      run: |
        cd "THJPatcher"
        dotnet publish "THJPatcher.sln" -c ${{env.BUILD_CONFIGURATION}} -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:VERSION="${{ env.VERSION }}.${{ github.run_number }}" /p:FILELIST_URL=${{env.FILELIST_URL}} /p:SERVER_NAME="${{env.SERVER_NAME}}" /p:FILE_NAME="${{env.FILE_NAME}}"

    - name: Debug Build Output
      run: |
        Write-Host "=== Current Directory ==="
        Get-Location
        Write-Host "`n=== Directory Structure ==="
        Get-ChildItem -Path "THJPatcher" -Recurse -Filter "*.exe" | ForEach-Object {
            Write-Host $_.FullName
            Write-Host "File size: $($_.Length) bytes"
        }

    - name: Generate File List
      run: |
        cd "rof"
        C:\msys64\usr\bin\wget.exe --no-verbose https://github.com/xackery/filelistbuilder/releases/latest/download/filelistbuilder-win-x64.exe
        Write-Host "=== Running FilelistBuilder ==="
        .\filelistbuilder-win-x64.exe "rof" "${{env.STORAGE_URL}}" "../THJPatcher/THJPatcher/bin/Release/net8.0-windows/win-x64/publish/THJPatcher.exe"
        move "../THJPatcher/THJPatcher/bin/Release/net8.0-windows/win-x64/publish/THJPatcher.exe" "../THJPatcher/THJPatcher/bin/Release/net8.0-windows/win-x64/publish/${{env.FILE_NAME}}.exe"
        move "eqemupatcher-hash.txt" "${{env.FILE_NAME}}-hash.txt"

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/master'
      with:
        tag_name: ${{ env.VERSION }}.${{ github.run_number }}
        name: Release ${{ env.VERSION }}.${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          THJPatcher/THJPatcher/bin/Release/net8.0-windows/win-x64/publish/${{env.FILE_NAME}}.exe
          rof/filelist_rof.yml
          rof/${{env.FILE_NAME}}-hash.txt
          manifest.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
